---
services:
  viewpicam:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: viewpicam
    restart: unless-stopped
    privileged: true
    volumes:
      - ./backend/data:/app/data
      - ./backend/macros:/app/macros
      - ./backend/h264:/app/h264
      - ./backend/config:/app/config
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 80:80

# WARNING --> Use command below because Viewpicam is not compatible AMD64
# DOCKER_DEFAULT_PLATFORM=linux/armhf docker compose up
# DOCKER_DEFAULT_PLATFORM=linux/armv6 docker compose up